### ISSUE TITLE
GetxController生命周期结束的时机为什么是“路由返回时”？

### ISSUE THREAD

**Issue by Dabbit-Chan** [h65wang/flutter_interview_questions#91]
如果SmartManagement不是full且没使用GetMaterialApp，路由返回应该不会触发GetxController的生命周期结束吧

**Comment by huanghui1998hhh** [comment]
感谢提醒，`SmartManagement`为`.onlyBuilder`的时候只会'only builder'，也就是对于`Get.put()`和`Get.putAsync()`注册的Controller(`Get.lazyPut()`不受影响)只负责"构建"，不负责"销毁"。
而`GetMaterialApp`的`navigatorObservers`中添加了`GetObserver()`，其中提供了全局取路由相关参数的魔法实现以及对`GetxController`的`onClose()`的自动管理。
也存在其他情况，例如使用`GetBuilder`的`init`参数构造出的Controller会被`GetBuilder`这个`StatefulWidget`在局部管理。
[本题](https://github.com/h65wang/flutter_interview_questions/blob/341ef8cb813b04185bc032c100aec2abe92d36e1/assets/questions/zh/getx_specialization.json#L21)还是想讨论在使用`GetxController`自动管理的情况下，`GetxController`的`onClose()`方法会在什么时机被调用。这也算是大家最常用的场景，初衷是因为经常看到很多老哥在群里问，为什么我的`GetxController`没有被"销毁"，所以有了这一题，考察使用者是否知晓在常用场景下`GetxController`的周期是与路由相关的。

**Comment by Dabbit-Chan** [comment]
这题我选的是“controller实例未被引用时”，他未被引用的话不会触发`onClose()`的吗？印象里controller被内存释放也会触发`onClose()`

**Comment by huanghui1998hhh** [comment]
所谓`GetxController`"销毁"，并不意味着从内存中释放，只是调用了`onClose()`方法，`GetxController`生命周期结束，我们则认为Controller被"销毁"了。真正有没有释放内存就是dart的事情了，也做不到某个类被释放时调用某个方法。

**Comment by Dabbit-Chan** [comment]
感谢，受教了
